name: Build and Deploy Code
on: [push, pull_request]

jobs:
  building:
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_NAME: fastapi_test
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      JWT_ALGORITHM: ${{secrets.JWT_ALGORITHM}}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.JWT_ACCESS_TOKEN_EXPIRE_MINUTES}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: fastapi_test
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: checking out code
        uses: actions/checkout@v4
      - name: say hello
        run: echo "hello moo"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install dependices
        run: pip install -r  requirements.txt
      - name: initiate testing
        run: |
          pip install pytest 
          pytest
    
  docker:
    runs-on: ubuntu-latest  
    steps:      
        - 
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: /home/runner/work/fastapi-social/fastapi-social/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi:latest